[package]
name = "simple-account-layer"
version = "0.1.0"
authors = ["hupeng <bitrocks.hu@gmail.com>"]
license = "MIT"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "simple_account_layer"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.4.0"

[dependencies]
neon = "0.4.0"
ckb-simple-account-layer = {git = "https://github.com/nervosnetwork/ckb-simple-account-layer", branch = "develop"}
